# Generated by Django 4.2.3 on 2023-08-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievence',
            options={'managed': True},
        ),
    ]
