# Generated by Django 4.2.3 on 2023-08-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_grievence_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievence',
            name='dno',
            field=models.ForeignKey(blank=True, db_column='dno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.department'),
        ),
        migrations.AddField(
            model_name='grievence',
            name='usn',
            field=models.ForeignKey(blank=True, db_column='usn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.student'),
        ),
        migrations.AlterField(
            model_name='grievence',
            name='gid',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
