# Generated by Django 4.2.3 on 2023-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_grievence_dno_grievence_usn_alter_grievence_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievence',
            name='gid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
