# Generated by Django 4.2.3 on 2023-08-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_grievence_gid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievence',
            options={'managed': False},
        ),
    ]
